#!/usr/bin/env bash
# Vendors Fluent System Icons (MIT, microsoft/fluentui-system-icons) as Avalonia
# StreamGeometry resources. Output: Icons.axaml next to this script.
set -euo pipefail
cd "$(dirname "$0")"
BASE="https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/assets"

# "snake_name|Folder Name|variant" — 20px size for all.
ICONS=(
  "task_list_square_ltr|Task List Square LTR|regular"
  "task_list_square_ltr|Task List Square LTR|filled"
  "grid|Grid|regular"
  "grid|Grid|filled"
  "arrow_swap|Arrow Swap|regular"
  "arrow_swap|Arrow Swap|filled"
  "document_text|Document Text|regular"
  "document_text|Document Text|filled"
  "settings|Settings|regular"
  "settings|Settings|filled"
  "server|Server|regular"
  "checkmark_circle|Checkmark Circle|regular"
  "checkmark|Checkmark|filled"
  "arrow_sync|Arrow Sync|regular"
  "arrow_clockwise|Arrow Clockwise|regular"
  "dismiss_circle|Dismiss Circle|regular"
  "key|Key|regular"
  "add|Add|regular"
  "info|Info|regular"
  "warning|Warning|regular"
  "error_circle|Error Circle|regular"
  "error_circle|Error Circle|filled"
  "chevron_down|Chevron Down|regular"
  "chevron_up|Chevron Up|regular"
  "chevron_right|Chevron Right|regular"
  "dismiss|Dismiss|regular"
  "play|Play|regular"
  "pause|Pause|regular"
  "hand_right|Hand Right|regular"
  "clock|Clock|regular"
  "arrow_upload|Arrow Upload|regular"
  "warning|Warning|filled"
  "search|Search|regular"
  "more_horizontal|More Horizontal|regular"
  "text_line_spacing|Text Line Spacing|regular"
  "apps_list|Apps List|regular"
  "group_list|Group List|regular"
  "edit|Edit|regular"
  "plug_connected|Plug Connected|regular"
  "play_settings|Play Settings|regular"
  "snooze|Snooze|regular"
  "delete|Delete|regular"
  "developer_board|Developer Board|regular"
  "developer_board_lightning|Developer Board Lightning|regular"
  "globe|Globe|regular"
)

pascal() { echo "$1" | awk -F_ '{ for (i=1;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }'; }

OUT=$(mktemp)
trap 'rm -f "$OUT"' EXIT
FINAL=Icons.axaml
{
  echo '<ResourceDictionary xmlns="https://github.com/avaloniaui"'
  echo '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">'
  echo '  <!-- GENERATED by generate-icons.sh. Fluent System Icons, MIT License,'
  echo '       (c) Microsoft Corporation — github.com/microsoft/fluentui-system-icons -->'
} > "$OUT"

for entry in "${ICONS[@]}"; do
  IFS='|' read -r snake folder variant <<< "$entry"
  url="$BASE/${folder// /%20}/SVG/ic_fluent_${snake}_20_${variant}.svg"
  svg=$(curl -sf "$url") || { echo "MISSING: $url" >&2; exit 1; }
  # NOTE: naive text extraction — assumes each upstream SVG is a single top-level <path>. Verify any NEW icon added to ICONS still fits that shape before trusting the output.
  d=$(echo "$svg" | grep -oE ' d="[^"]+"' | sed -E 's/ d="([^"]+)"/\1/' | tr '\n' ' ' | sed 's/ $//' || true)
  [ -n "$d" ] || { echo "NO PATH DATA: $url" >&2; exit 1; }
  suffix=$([ "$variant" = "filled" ] && echo Filled || echo Regular)
  echo "  <StreamGeometry x:Key=\"Icon$(pascal "$snake")$suffix\">$d</StreamGeometry>" >> "$OUT"
done
echo '</ResourceDictionary>' >> "$OUT"
chmod 644 "$OUT"
mv "$OUT" "$FINAL"
echo "generated $FINAL with $(grep -c StreamGeometry "$FINAL") geometries"
