#!/usr/bin/env bash
# Vendors Fluent System Icons (MIT, microsoft/fluentui-system-icons) as Avalonia
# StreamGeometry resources. Output: Icons.axaml next to this script.
set -euo pipefail
cd "$(dirname "$0")"
BASE="https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/assets"

# "snake_name|Folder Name|variant" — 20px size for all.
ICONS=(
  "task_list_square_ltr|Task List Square LTR|regular"
  "task_list_square_ltr|Task List Square LTR|filled"
  "grid|Grid|regular"
  "grid|Grid|filled"
  "arrow_swap|Arrow Swap|regular"
  "arrow_swap|Arrow Swap|filled"
  "document_text|Document Text|regular"
  "document_text|Document Text|filled"
  "settings|Settings|regular"
  "settings|Settings|filled"
  "server|Server|regular"
  "checkmark_circle|Checkmark Circle|regular"
  "arrow_sync|Arrow Sync|regular"
  "arrow_clockwise|Arrow Clockwise|regular"
  "dismiss_circle|Dismiss Circle|regular"
  "key|Key|regular"
  "add|Add|regular"
  "info|Info|regular"
  "warning|Warning|regular"
  "error_circle|Error Circle|regular"
  "chevron_down|Chevron Down|regular"
  "chevron_up|Chevron Up|regular"
  "chevron_right|Chevron Right|regular"
  "dismiss|Dismiss|regular"
)

pascal() { echo "$1" | awk -F_ '{ for (i=1;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }'; }

OUT=Icons.axaml
{
  echo '<ResourceDictionary xmlns="https://github.com/avaloniaui"'
  echo '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">'
  echo '  <!-- GENERATED by generate-icons.sh. Fluent System Icons, MIT License,'
  echo '       (c) Microsoft Corporation — github.com/microsoft/fluentui-system-icons -->'
} > "$OUT"

for entry in "${ICONS[@]}"; do
  IFS='|' read -r snake folder variant <<< "$entry"
  url="$BASE/${folder// /%20}/SVG/ic_fluent_${snake}_20_${variant}.svg"
  svg=$(curl -sf "$url") || { echo "MISSING: $url" >&2; exit 1; }
  d=$(echo "$svg" | grep -oE ' d="[^"]+"' | sed -E 's/ d="([^"]+)"/\1/' | tr '\n' ' ' | sed 's/ $//')
  [ -n "$d" ] || { echo "NO PATH DATA: $url" >&2; exit 1; }
  suffix=$([ "$variant" = "filled" ] && echo Filled || echo Regular)
  echo "  <StreamGeometry x:Key=\"Icon$(pascal "$snake")$suffix\">$d</StreamGeometry>" >> "$OUT"
done
echo '</ResourceDictionary>' >> "$OUT"
echo "generated $OUT with $(grep -c StreamGeometry "$OUT") geometries"
